[features]
seeds = false

[programs.localnet]
dispute = "GyXfrEB6iF7zDnrvte9WVjMW8fgTG8URhWvWYADS39dZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "../config/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
